In [1]:
from transformers import BertModel,AutoTokenizer
from bertviz import head_view
import pandas as pd
import numpy as np
import torch

C:\Users\verma\anaconda3\envs\llm_env\lib\site-packages\transformers\utils\generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(


In [2]:
torch.__version__

'2.2.0+cpu'

In [3]:
#! pip install bertviz

In [4]:
model_name="bert-base-cased"

In [5]:
tokenizer=AutoTokenizer.from_pretrained(model_name)
model=BertModel.from_pretrained(model_name)

In [6]:
text_input="I am studying large language models, also referred to as foundation models"

In [7]:
token=tokenizer.encode(text_input)

In [8]:
token

[101,
 146,
 1821,
 5076,
 1415,
 1846,
 3584,
 117,
 1145,
 2752,
 1106,
 1112,
 4686,
 3584,
 102]

In [9]:
inputs=torch.tensor(token).unsqueeze(0)

In [10]:
inputs

tensor([[ 101,  146, 1821, 5076, 1415, 1846, 3584,  117, 1145, 2752, 1106, 1112,
         4686, 3584,  102]])

In [11]:
attention=model(inputs,output_attentions=True)[2]

In [12]:
attention

(tensor([[[[6.1486e-01, 6.1029e-03, 3.0787e-03,  ..., 8.2891e-03,
            4.3950e-03, 2.8221e-01],
           [8.6124e-02, 6.5548e-03, 1.7970e-01,  ..., 4.8129e-02,
            6.1356e-02, 1.0163e-01],
           [2.7122e-01, 1.5646e-02, 8.5203e-02,  ..., 3.7912e-02,
            1.1033e-01, 4.3252e-02],
           ...,
           [1.5577e-01, 4.2397e-02, 1.2386e-01,  ..., 4.5274e-02,
            5.3269e-02, 1.3230e-01],
           [2.3193e-01, 2.7710e-02, 5.4243e-02,  ..., 3.2005e-02,
            1.5898e-01, 6.3478e-02],
           [2.8989e-01, 3.8735e-03, 1.2164e-02,  ..., 3.9960e-03,
            1.3988e-03, 6.3474e-01]],
 
          [[4.9722e-01, 3.6044e-02, 4.2341e-02,  ..., 4.7066e-02,
            1.6457e-02, 2.8695e-02],
           [9.8610e-02, 2.0979e-01, 1.5112e-01,  ..., 1.8976e-02,
            2.9148e-03, 6.5309e-03],
           [3.3597e-02, 7.1047e-01, 3.3142e-02,  ..., 8.0556e-03,
            3.7760e-03, 2.6419e-03],
           ...,
           [1.0422e-02, 1.3369e-02, 1.

In [13]:
final_attention=attention[-1].mean(1)[0]

In [14]:
attention_df=pd.DataFrame(final_attention.detach()).applymap(float).round(3)
attention_df.columns=tokenizer.convert_ids_to_tokens(token)
attention_df.index=tokenizer.convert_ids_to_tokens(token)
attention_df

C:\Users\verma\AppData\Local\Temp\ipykernel_4056\1354143301.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  attention_df=pd.DataFrame(final_attention.detach()).applymap(float).round(3)


[CLS]      I     am  studying  large  language  models      ,  \
[CLS]       0.075  0.051  0.052     0.083  0.057     0.077   0.076  0.021   
I           0.017  0.065  0.022     0.021  0.016     0.031   0.020  0.008   
am          0.010  0.016  0.125     0.043  0.008     0.012   0.013  0.005   
studying    0.012  0.010  0.013     0.238  0.015     0.016   0.023  0.005   
large       0.017  0.018  0.010     0.024  0.217     0.063   0.035  0.007   
language    0.010  0.012  0.008     0.013  0.033     0.139   0.041  0.006   
models      0.013  0.008  0.006     0.011  0.026     0.071   0.184  0.010   
,           0.016  0.016  0.013     0.014  0.014     0.014   0.015  0.165   
also        0.005  0.004  0.004     0.005  0.003     0.004   0.003  0.007   
referred    0.005  0.002  0.002     0.004  0.002     0.002   0.003  0.003   
to          0.006  0.003  0.003     0.004  0.004     0.002   0.002  0.005   
as          0.010  0.005  0.005     0.014  0.022     0.010   0.007  0.010   
foundation  0.011  0.009  0.005     0.013  0.052     0.112   0.040  0.003   
models      0.036  0.013  0.012     0.020  0.023     0.060   0.076  0.013   
[SEP]       0.059  0.069  0.059     0.066  0.071     0.078   0.076  0.059   

             also  referred     to     as  foundation  models  [SEP]  
[CLS]       0.007     0.007  0.003  0.010       0.051   0.106  0.324  
I           0.003     0.002  0.001  0.003       0.010   0.016  0.765  
am          0.002     0.001  0.001  0.003       0.006   0.010  0.745  
studying    0.002     0.002  0.001  0.002       0.007   0.016  0.639  
large       0.003     0.002  0.001  0.006       0.033   0.018  0.546  
language    0.002     0.001  0.001  0.004       0.025   0.017  0.688  
models      0.002     0.002  0.001  0.004       0.024   0.057  0.582  
,           0.035     0.016  0.007  0.012       0.010   0.021  0.634  
also        0.235     0.019  0.004  0.005       0.003   0.004  0.696  
referred    0.031     0.221  0.003  0.005       0.003   0.004  0.709  
to          0.021     0.013  0.230  0.011       0.003   0.003  0.689  
as          0.037     0.028  0.022  0.163       0.009   0.007  0.650  
foundation  0.001     0.001  0.001  0.004       0.117   0.018  0.613  
models      0.003     0.002  0.001  0.004       0.025   0.194  0.519  
[SEP]       0.045     0.051  0.047  0.059       0.073   0.079  0.108

In [15]:
attention_df.shape

(15, 15)

In [16]:
token_as_list=tokenizer.convert_ids_to_tokens(inputs[0])
head_view(attention,token_as_list)

<IPython.core.display.Javascript object>

## Masked Language Modeling 

In [18]:
from transformers import AutoModelForMaskedLM,AutoTokenizer
from scipy.special import softmax

In [19]:
# Defining the model name
# Loading the pre-trained model and tokenizer
model = AutoModelForMaskedLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'bert.pooler.dense.weight', 'bert.pooler.dense.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [20]:
# Defining the mask token
mask = tokenizer.mask_token
# Defining the sentence
sentence = f"I want to {mask} pizza for tonight."
# Tokenizing the sentence
tokens = tokenizer.tokenize(sentence)

In [21]:
mask

'[MASK]'

In [22]:
sentence

'I want to [MASK] pizza for tonight.'

In [23]:
tokens

['I', 'want', 'to', '[MASK]', 'pizza', 'for', 'tonight', '.']

In [24]:
# Encoding the input sentence and getting model predictions
encoded_inputs=tokenizer(sentence,return_tensors='pt')

In [25]:
output=model(**encoded_inputs)

In [26]:
output.logits

tensor([[[ -7.3723,  -7.2489,  -7.4421,  ...,  -6.3119,  -5.9369,  -6.4257],
         [ -7.9311,  -8.2282,  -8.0326,  ...,  -6.7387,  -6.4877,  -6.9525],
         [-12.0500, -11.7972, -12.5776,  ...,  -8.4518,  -6.7310,  -8.2586],
         ...,
         [-10.2204, -10.4315,  -9.9993,  ...,  -7.9570,  -6.7194,  -9.3618],
         [-12.4471, -12.5367, -12.5614,  ...,  -9.9086,  -9.4219, -11.1770],
         [-14.3657, -14.5227, -15.0017,  ..., -11.9715, -11.6569, -13.4498]]],
       grad_fn=<ViewBackward0>)

In [27]:
# Detaching the logits from the model output and converting to numpy array
logits = output.logits.detach().numpy()[0]

In [28]:
logits

array([[ -7.372293 ,  -7.2488613,  -7.4421434, ...,  -6.311862 ,
         -5.9368916,  -6.425681 ],
       [ -7.931119 ,  -8.22821  ,  -8.032589 , ...,  -6.7387447,
         -6.4877234,  -6.952524 ],
       [-12.05001  , -11.797207 , -12.577608 , ...,  -8.451774 ,
         -6.7310166,  -8.258563 ],
       ...,
       [-10.220416 , -10.431487 ,  -9.999262 , ...,  -7.956997 ,
         -6.719405 ,  -9.361798 ],
       [-12.4471245, -12.536705 , -12.561405 , ...,  -9.908554 ,
         -9.421911 , -11.176953 ],
       [-14.365713 , -14.5227165, -15.001675 , ..., -11.971548 ,
        -11.656923 , -13.449784 ]], dtype=float32)

In [29]:
# Extracting the logits for the masked token and calculating the confidence scores
masked_logits = logits[tokens.index(mask) + 1]
confidence_scores = softmax(masked_logits)

In [30]:
masked_logits

array([-6.714629 , -6.3791075, -6.1184883, ..., -5.651307 , -3.657277 ,
       -4.994729 ], dtype=float32)

In [31]:
confidence_scores

array([2.9159949e-10, 4.0785136e-10, 5.2928190e-10, ..., 8.4446339e-10,
       6.2026464e-09, 1.6282800e-09], dtype=float32)

In [32]:
# Iterating over the top 5 predicted tokens and printing the sentences with the masked token replaced
for i in np.argsort(confidence_scores)[::-1][:5]:
    pred_token = tokenizer.decode(i)
    score = confidence_scores[i]

    # print(pred_token, score)
    print(sentence.replace(mask, pred_token))

I want to have pizza for tonight.
I want to get pizza for tonight.
I want to eat pizza for tonight.
I want to make pizza for tonight.
I want to order pizza for tonight.
